{% set version = "3.18.0" %}

package:
    name: freeimage
    version: {{ version }}

source:
  - url: http://downloads.sourceforge.net/freeimage/FreeImage3180.zip
    sha256: f41379682f9ada94ea7b34fe86bf9ee00935a3147be41b6569c9605a53e438fd

build:
  number: 1
  skip: true  # [win]
  binary_relocation: False  # [osx]
  run_exports:
    - {{ pin_subpackage('freeimage', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - make  # [unix]
    # need to convert line endings for the patches to work
    - dos2unix  # [unix]
  host:
    - jpeg
    - openjpeg
    - jxrlib
    - libtiff
    - openexr
    - ilmbase
    - libpng
    - zlib
    - libraw
    - libwebp

test:
  commands:
    - test -f $PREFIX/lib/libfreeimage${SHLIB_EXT}  # [linux]
    - test -f $PREFIX/lib/libfreeimage${SHLIB_EXT}.3  # [linux]
    - test -f $PREFIX/lib/libfreeimage.3${SHLIB_EXT}  # [osx]
    - test -f $PREFIX/lib/libfreeimage-{{ version }}${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/FreeImage.h  # [unix]

about:
  home: http://freeimage.sourceforge.net/
  license: GPLv2 GPLv3 FreeImage
  license_file:
      - license-fi.txt
      - license-gplv2.txt
      - license-gplv3.txt
  summary: Helps provide support for many common image formats (PNG, JPEG, TIFF, BMP and others).

extra:
  recipe-maintainers:
    - almarklein
    - jakirkham
    - msarahan
    - wolfv
    - seanyen
