# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Nr6+aRf3Hgj+sJTHLhHd2654boUpQyuuAama0VpCVD0b8Kezd3KbjP0QdswTFbgY+bQBB4QhDmIk8PJ+snyWwuP0lpHqQiNRwwtyKAVjmp+tg3moiLcwWK6pcXTANqlFDrGIP9aQ/arEE10cxLr2UiZ1NYJXLgwsfT3rYxGdSJ6A0+vPgZf9Nzx3IIy+KuC6rrogoFZeUA75bODF0Oz2XSByomt02boxBbLEIdHTybA8pBBZbfDwfN8DSjkORJ90czOtbdD+BCF9/D7oUO0oN9UkEFb1/cBoOebvMaJgBZN+2dfEA/H7eHQpzCFqsiSCBlfYGCxn/lsvcjp9NiPIIAZlYHoVeKGTtTmlDt7Y4SPk2irfx8nZ0v0FrtrVWjTjU+srzwjOhBg23pIqG4esTRGoQDXaGfIHvljT5eHP9v4MXv+0PSHcGjo4wsg60e5+LuLL5UWbbU3ocvvZ9RPfVyGaPMxdWhkoNuCwf5IwgqtFuoKO4AmbmuS3vMNXhF4PEciO4SIDTzonkHGcLSS7f37DOQqVqtaQhCw3NHms4BHwh6jjIjcHVcz0Qw9BMRLo/aPMxp7KS7zzveUpLLrOoOiKAunciHJDixiQ4IfJP5hxmYm7BMGmqpMpMlyE3yuo6Y0ywYvasjtdJtuM5L3bx08q5sNLgIi2ArQYoiWO23s="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
