travis:
  secure:
    BINSTAR_TOKEN: f4xWGmsi9GqZVefrzoOrmWKgnVZdXP+YqM0EYGojfKgOIU6o+YUtRvfmdwu+ZXE7prV6Gff175H1L+oiumsuJKj0WvwBKh/aJueYp8hes/Dtqd6KxWKcIBsVjcinHvH28c8CNUBbppfJadohetwnprNFkkPP3cvfScqnsYdSMrcPfV/3Vp9c3tbNNCeGz223AVh5us64tV6yGxyvT0v0Gq5xBiDbpWauD3q80p3uO3BwQFqt9t+e+n5g6WFYI0G5tCwoQdAdZbWh47GxcVjCU6aolmTJ4ZIn0y1NsA+tyFuZcbbDXe5aXafI3tZFM6rclpizawwpsYSvtaxE/dDP3Bmmmx5Gi6RiPlk3cXkm7J/ZSIxJhuI5wyLseP2N3YxI68A0p9naXDSHMapVTMwRZnuSZLZD1rj6yjHf3JV4k+GP7NR1dGtcDIU+ljw4zw4Qrz/CI0L5hQjZYE/qmSnTexLq7XfpN9g9Ec6rKGhtl9F6V8ABRTfcXiULVBoWo1JdzsG1Ul7XN1W/8VP1vSvwlzUiH6I2Iyg6/b78YUZKeoNztHJ3L6a86W6DFI4e2PC2zvwt2LRW3sxFJI0vLXeoGxPTgfoT2Tv6rWqyWkyL8CsBKBK58Sg4Mhy0/m4ETrbsXs7vIvcZ3HqYkPXndnoRzpRrdr6TXHr1Ika6PXZBwnU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
