travis:
  secure:
    BINSTAR_TOKEN: Nr6+aRf3Hgj+sJTHLhHd2654boUpQyuuAama0VpCVD0b8Kezd3KbjP0QdswTFbgY+bQBB4QhDmIk8PJ+snyWwuP0lpHqQiNRwwtyKAVjmp+tg3moiLcwWK6pcXTANqlFDrGIP9aQ/arEE10cxLr2UiZ1NYJXLgwsfT3rYxGdSJ6A0+vPgZf9Nzx3IIy+KuC6rrogoFZeUA75bODF0Oz2XSByomt02boxBbLEIdHTybA8pBBZbfDwfN8DSjkORJ90czOtbdD+BCF9/D7oUO0oN9UkEFb1/cBoOebvMaJgBZN+2dfEA/H7eHQpzCFqsiSCBlfYGCxn/lsvcjp9NiPIIAZlYHoVeKGTtTmlDt7Y4SPk2irfx8nZ0v0FrtrVWjTjU+srzwjOhBg23pIqG4esTRGoQDXaGfIHvljT5eHP9v4MXv+0PSHcGjo4wsg60e5+LuLL5UWbbU3ocvvZ9RPfVyGaPMxdWhkoNuCwf5IwgqtFuoKO4AmbmuS3vMNXhF4PEciO4SIDTzonkHGcLSS7f37DOQqVqtaQhCw3NHms4BHwh6jjIjcHVcz0Qw9BMRLo/aPMxp7KS7zzveUpLLrOoOiKAunciHJDixiQ4IfJP5hxmYm7BMGmqpMpMlyE3yuo6Y0ywYvasjtdJtuM5L3bx08q5sNLgIi2ArQYoiWO23s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
